services:
  nextcloud:
    image: docker.io/library/nextcloud:apache
    ports:
      - "8080:80"
    environment:
      SQLITE_DATABASE: nextcloud
      NEXTCLOUD_ADMIN_USER: pi
      NEXTCLOUD_ADMIN_PASSWORD: nlu@2026
      NEXTCLOUD_TRUSTED_DOMAINS: ${NEXTCLOUD_TRUSTED_DOMAINS}
      PHP_MEMORY_LIMIT: 128M
      PHP_UPLOAD_LIMIT: 2G
    volumes:
      - ${NEXTCLOUD_DIR}/html:/var/www/html
      - ${NEXTCLOUD_DIR}/data:/var/www/html/data
    mem_limit: 512m
    restart: unless-stopped
