services:
  web-vnc:
    build:
      context: .
      dockerfile: Dockerfile-web-vnc
    image: raspberry-pi-workshop/web-vnc:latest
    container_name: web_vnc
    network_mode: host
    environment:
      DISPLAY: ${DISPLAY:-:0}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
      - /run:/run:ro
      - /home:/home:ro
    restart: unless-stopped
